(fix) Allow opening legacy html forms on visit list
openmrs/openmrs-esm-patient-chart pull request #1027
Opened 2023-02-28 10:11 UTC by icrc-psousa

## Requirements

- [x] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [x] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide).
- [ ] My work includes tests or is validated by existing tests.

## Summary
This fix will allow editing encounters recorded on HTMLFormEntry from the visits list. Prior to this fix, if the user tried to open a legacy form, an error would occur.
The configuration used to check whether a form is legacy html or not is the same already in place for the "Forms & Notes" list.

## Screenshots
![image](https://user-images.githubusercontent.com/68599335/221821565-bfc35e87-a3a4-4113-bb49-644cf11fc263.png)

2023-03-02 21:07 UTC, ibacher requested changes
Thanks for this. This doesn't look like it's properly formatted according to our standards (which should be happening on commit, but if you've disabled that hook, you do need to run it). A few other things to fix highlighted below.

2023-03-02 21:07 UTC, ibacher commented on packages/esm-patient-chart-app/src/visit/visits-widget/past-visits-components/visits-table/visits-table.component.tsx
> +  const [htmlFormEntryFormsConfig, setHtmlFormEntryFormsConfig] = React.useState<null | Array<HtmlFormEntryForm>>(null);
```suggestion
  const [htmlFormEntryFormsConfig, setHtmlFormEntryFormsConfig] = useState<Array<HtmlFormEntryForm> | undefined>();
```

2023-03-02 21:07 UTC, ibacher commented on packages/esm-patient-chart-app/src/visit/visits-widget/past-visits-components/visits-table/visits-table.component.tsx
> +    const htmlForm = htmlFormEntryFormsConfig.find((form) => form.formUuid === formUuid);
```suggestion
    const htmlForm = htmlFormEntryFormsConfig?.find((form) => form.formUuid === formUuid);
```

2023-03-02 21:07 UTC, ibacher commented on packages/esm-patient-chart-app/src/visit/visits-widget/past-visits-components/visits-table/visits-table.component.tsx
> +import {HtmlFormEntryForm} from "@openmrs/esm-patient-forms-app/src/config-schema";
```suggestion
import type {HtmlFormEntryForm} from "@openmrs/esm-patient-forms-app/src/config-schema";
```

2023-03-02 21:19 UTC, denniskigen commented on packages/esm-patient-chart-app/src/visit/visits-widget/visit-detail-overview.test.tsx
> +    mockGetConfig.mockReturnValue(Promise.resolve({ htmlFormEntryForms: [] }));
```suggestion
    mockGetConfig.mockResolvedValue({ htmlFormEntryForms: [] });
```

2023-03-02 21:19 UTC, denniskigen commented on packages/esm-patient-chart-app/src/visit/visits-widget/visit-detail-overview.test.tsx
> +    mockGetConfig.mockReturnValue(Promise.resolve({ htmlFormEntryForms: [] }));
```suggestion
     mockGetConfig.mockResolvedValue({ htmlFormEntryForms: [] });
```

2023-03-03 19:36 UTC, ibacher approved these changes

2023-03-03 19:37 UTC, ibacher commented
Another solution I don't love, but until we have something better, I don't think we have any choice but introducing this level of coupling.

2023-03-03 19:37 UTC, merged