Model Object now also handles 'other' and 'unknown' genders.
openmrs/openmrs-esm-patient-chart pull request #1042
Opened 2023-03-13 08:29 UTC by VivekAlladi

## Requirements

- [ ] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide).
- [ ] My work includes tests or is validated by existing tests.

## Summary

I'm working on displaying Pictograms on Ampath forms based on the gender of the patient. Currently, I'm able to render options for male and female patients based on **model['sex'] = 'M' or 'F'**. I have now slightly modified model object such that now it also stores 'O' for other and 'U' for unknown genders. 

[https://tfs.ext.icrc.org/ICRCCollection/Pearlii/_sprints/backlog/ThoughtWorks/Pearlii/Application/EMR/ThoughtWorks/2023/2023%20Sprint%205?workitem=349498]

## Screenshots

## Related Issue

## Other

2023-03-24 09:33 UTC, jnsereko commented on packages/esm-form-entry-app/src/app/form-data-source/form-data-source.service.ts
> +          return 'M';
Why is the default gender Male? Realistically, you can't an individual's gender until he/she tell you.

2023-03-24 09:35 UTC, jnsereko requested changes
Why is the default gender Male? Realistically, you can't an individual's gender until he/she tell you.

2023-03-24 09:35 UTC, jnsereko commented on packages/esm-form-entry-app/src/app/form-data-source/form-data-source.service.ts
> +          return 'M';
```suggestion
          return 'U';
```

2023-04-11 19:15 UTC, denniskigen approved these changes

2023-04-11 19:27 UTC, denniskigen approved these changes
Thanks, @VivekAlladi.

2023-04-11 19:29 UTC, merged