(fix) Encounter edit and deletion should b handled through permissions
openmrs/openmrs-esm-patient-chart pull request #1190
Opened 2023-06-05 04:39 UTC by Jexsie

## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [x] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://zeroheight.com/23a080e38/p/880723-introduction).
- [x] My work includes tests or is validated by existing tests.

## Summary

This PR updates the following;
- `All encounters` tab to be displayed through config.
- User with right access to that encounter can edit and delete it.
- User without right access to the encounter only sees `Go to this encounter` button and OverflowMenuItem

## Screenshots
![image](https://github.com/openmrs/openmrs-esm-patient-chart/assets/104269786/5fb85bf1-2b57-4e95-931c-a189731b67e9)

## Screencasts

[Screencast from 2023-06-05 07-32-33.webm](https://github.com/openmrs/openmrs-esm-patient-chart/assets/104269786/0b0c61c2-c679-4e89-a58c-a0607daaf6bb)

## Related Issue

## Other

2023-06-05 04:42 UTC, Jexsie commented on packages/esm-patient-chart-app/src/config-schema.ts
> +    _default: true,
made it true by default

2023-06-05 05:14 UTC, Jexsie commented
I have noticed a couple of things here. We basically have two tables that are supposed to handle the same thing. The [`EncountersTable`](https://github.com/openmrs/openmrs-esm-patient-chart/blob/main/packages/esm-patient-chart-app/src/visit/visits-widget/encounters-table/encounters-table.component.tsx#LL51C1-L51C1) and the [`VisitTable`](https://github.com/openmrs/openmrs-esm-patient-chart/blob/main/packages/esm-patient-chart-app/src/visit/visits-widget/past-visits-components/visits-table/visits-table.component.tsx#L60).
The `EncountersTable` is used nowhere in our code. It was actually meant to be used on the `All encounters` tab where the `VisitTable` is working very fine. I think we need to clean it up.

Secondly, we have two hooks that can actually do the same thing. The [`useVisits`](https://github.com/openmrs/openmrs-esm-patient-chart/blob/main/packages/esm-patient-chart-app/src/visit/visits-widget/visit.resource.tsx#L4) and [`usePastVisits`](https://github.com/openmrs/openmrs-esm-patient-chart/blob/main/packages/esm-patient-chart-app/src/visit/visits-widget/visit.resource.tsx#L50). I think `useVisits` is sufficient for all tasks related to visits and encounters.

cc @vasharma05 @ibacher @denniskigen @kumuditha-udayanga

2023-06-05 05:18 UTC, Jexsie commented on packages/esm-patient-chart-app/src/visit/visits-widget/past-visits-components/visits-table/visits-table.component.tsx
> +                          </Button>
a user without access to the encounter will see `Go to this encounter`. Is `Document` the right icon to display here?

2023-06-05 05:21 UTC, Jexsie commented on packages/esm-patient-chart-app/src/visit/visits-widget/visit-detail-overview.component.tsx
> -}
moved this to `visit.resource.tsx` since it is reusable

2023-06-05 14:27 UTC, ibacher requested changes
Just a few quick comments. Thanks for the work on this @Jexsie!

2023-06-05 18:51 UTC, Jexsie commented on packages/esm-patient-chart-app/src/visit/visits-widget/visit-detail-overview.component.tsx
> +      return mapEncounters(
Yeah, I just got confused about something.

2023-06-15 11:54 UTC, ibacher approved these changes

2023-06-15 11:54 UTC, merged