Print feature
openmrs/openmrs-esm-patient-chart pull request #1196
Opened 2023-06-07 10:30 UTC by nanfuka

## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [x] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://zeroheight.com/23a080e38/p/880723-introduction).
- [ ] My work includes tests or is validated by existing tests.

## Summary

This PR implements the print feature. This feature will later be implemented in the esm core, however for testing purposes, I have implemented it in the vitals package with in the patient chart.

## Screenshots

## Related Issue

https://wiki.openmrs.org/pages/viewpage.action?pageId=4489284

## Other

2023-06-07 11:02 UTC, nanfuka commented
@hadijahkyampeire and @denniskigen kindly review.

2023-06-08 11:59 UTC, hadijahkyampeire requested changes
Thanks, @nanfuka for the progress, just a few things plus good [PR conventions](https://o3-docs.vercel.app/docs/frontend-modules/contributing#contributing-guidelines). The title Print feature is too big, it should probably be `(feat) Implement the print functionality for Vitals lists`. 
Remember this print functionality is going to appear in many places, so the PR should have a title that clearly state exactly what it is changing.

2023-06-08 12:07 UTC, hadijahkyampeire commented on packages/esm-patient-vitals-app/src/vitals/print-this.component.tsx
> +        {t('print', 'Print')}
This should probably be just more than `print`, something like `print vitals`. This is because you will have many of these in many places.

2023-06-08 12:10 UTC, hadijahkyampeire commented on packages/esm-patient-vitals-app/src/vitals/print-this.component.tsx
> +        {t('print', 'Print')}
Actually, looking at where the button is, just print might be okay since it is inside the Vitals table

2023-06-21 11:23 UTC, hadijahkyampeire commented
@nanfuka I don't see the header when I test the branch locally. Also please fix the failing tests.

2023-06-21 11:25 UTC, hadijahkyampeire commented on packages/esm-patient-vitals-app/src/vitals/paginated-vitals.component.tsx
> +import { orderBy } from 'lodash-es';
```suggestion
import { orderBy } from 'lodash-es';
import orderBy from 'lodash-es/orderBy';
```

2023-06-21 11:28 UTC, hadijahkyampeire commented on packages/esm-patient-vitals-app/src/vitals/paginated-vitals.component.tsx
> +      {!printClicked ? (
Why does this pagination depend on the print being clicked?

2023-06-21 11:28 UTC, hadijahkyampeire commented on packages/esm-patient-vitals-app/src/vitals/print/print.component.tsx
> +          <footer className={`${styles.footer} `}>
Let's remove the comments

2023-06-21 11:29 UTC, hadijahkyampeire commented on packages/esm-patient-vitals-app/src/vitals/vitals-overview.component.tsx
> +    documentTitle: '',
I think we should pass a title as `Patient vitals`

2023-06-21 13:13 UTC, denniskigen commented on packages/esm-patient-vitals-app/src/config-schema.ts
> +      _description: 'Whether to use the print feature on the vitals list. If set to true,the print button will display',
```suggestion
      _description: 'Determines whether or not to display the Print button in the vitals datatable header. If set to true, a Print button gets shown as the right-most item in the table header. When clicked, this button enables the user to print out the contents of the table',
```

2023-06-21 13:13 UTC, denniskigen commented on packages/esm-patient-vitals-app/src/config-schema.ts
> +    showPrint: {
```suggestion
    showPrintButton: {
```

2023-06-21 13:13 UTC, denniskigen commented on packages/esm-patient-vitals-app/src/config-schema.ts
> +    showPrint: boolean;
Same as above

2023-06-21 13:14 UTC, denniskigen commented on packages/esm-patient-vitals-app/translations/en.json
> +  "RequestedBy": "Requested By",
```suggestion
  "requestedBy": "Requested by",
```

2023-06-21 13:15 UTC, denniskigen commented on packages/esm-patient-vitals-app/src/vitals/print/print.scss
> +
```suggestion
@media screen {
	.printpage {
		display: none;
	}
}

.patientDetails {
	margin-top: 3.5rem;
	text-align: center;
	column-count: 2;
	font-weight: bolder;
}

.subheader {
	text-align: center;
	font-weight: bolder;
}

.footer {
	text-align: center;
	margin-top: 1rem;
	font-weight: 400;
}

.requestedby {
	text-align: center;
}
```

2023-06-21 13:27 UTC, denniskigen commented on packages/esm-patient-vitals-app/src/vitals/paginated-vitals.component.tsx
> +  printClicked: boolean;
```suggestion
  printButtonClicked: boolean;
```

2023-06-21 13:27 UTC, denniskigen commented on packages/esm-patient-vitals-app/src/vitals/paginated-vitals.component.tsx
> +  printClicked,
```suggestion
  printButtonClicked,
```

2023-06-21 14:27 UTC, denniskigen commented on packages/esm-patient-vitals-app/src/vitals/paginated-vitals.component.tsx
> +
```suggestion
  const rows = isPrinting ? sortedData : paginatedVitals;

```

2023-06-21 14:27 UTC, denniskigen commented on packages/esm-patient-vitals-app/src/vitals/paginated-vitals.component.tsx
> +        rows={rowvalue}
```suggestion
        rows={rows}
```

2023-06-21 14:31 UTC, denniskigen commented on packages/esm-patient-vitals-app/src/vitals/paginated-vitals.component.tsx
>    tableHeaders: Array<any>;
```suggestion
  tableHeaders: Array<{ key: string; header: string }>;
```

2023-06-21 14:39 UTC, denniskigen commented on packages/esm-patient-vitals-app/src/vitals/vitals-overview.component.tsx
> +  };
```suggestion
   const patientDetails = useMemo(
    () => ({
      name: patient?.patient?.name?.[0].given + ' ' + patient?.patient?.name?.[0].family,
      age: parseInt(age(patient?.patient?.birthDate)),
      gender: patient?.patient?.gender,
      location: patient?.patient?.address?.[0].city,
    }),
    [patient],
  );
```

2023-07-04 20:06 UTC, denniskigen commented on packages/esm-patient-vitals-app/src/vitals/print/print.scss
> +        display: none;
Fix the indentation in this file. We use a tab size of `2` by default. If your editor is not set up to do this by default, press CTRL + Shift + P and type `Indent using Tabs` and set the configured tab size to `2`.

2023-07-13 09:10 UTC, hadijahkyampeire approved these changes
Thank you so much @nanfuka for this great work, let's merge it and move forward.

2023-07-13 10:10 UTC, denniskigen commented
Maybe best to get some final design feedback on today's squad call before merging.

2023-07-25 10:33 UTC, merged

2023-07-25 10:36 UTC, denniskigen commented
Good start, @nanfuka. Keen to see how this work progresses.

2023-07-28 04:02 UTC, nanfuka commented
thanks @denniskigen