Cache dependencies in Github Actions.
openmrs/openmrs-esm-patient-chart pull request #1198
Opened 2023-06-08 05:28 UTC by RandilaP

## Requirements

- [ ] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://zeroheight.com/23a080e38/p/880723-introduction).
- [ ] My work includes tests or is validated by existing tests.

## Summary
During the process of updating the patient chart, a timeout error occurred in the end-to-end GitHub actions. The objective of this PR is to resolve the underlying issue to ensure proper functionality.

## Screenshots

## Related Issue

https://issues.openmrs.org/browse/O3-2175

## Other

2023-06-08 05:42 UTC, RandilaP commented
@jayasanka-sack @anjula-sack @denniskigen @Piumal1999 Could you please review this

2023-06-08 05:51 UTC, jayasanka-sack requested changes
There are some changes to the lock file. Could you please undo those changes?

2023-06-09 13:57 UTC, anjula-sack commented on .github/workflows/e2e.yml
> +        uses: actions/cache@v3
```suggestion
            id: cache
            uses: actions/cache@v3
```

Here as well

2023-06-09 13:57 UTC, anjula-sack commented on .github/workflows/e2e.yml
> +        if: steps.cache.outputs.cache-hit != 'true'
```suggestion
            if: steps.cache.outputs.cache-hit != 'true'
```

2023-06-11 04:13 UTC, RandilaP commented on .github/workflows/e2e.yml
> +        uses: actions/cache@v3
It shows invalid child statement error

2023-06-11 04:16 UTC, anjula-sack commented on .github/workflows/e2e.yml
> +        uses: actions/cache@v3
yeah it's correct my bad

2023-06-12 16:31 UTC, anjula-sack commented on .github/workflows/e2e.yml
>            node-version: 16
Shall we try changing the node versiom

2023-08-08 02:41 UTC, Piumal1999 commented
Hi @RandilaP, Could you please resolve the conflicts and update the PR? The cache will work now. Refer to esm-patient-management if needed.

2023-08-15 06:47 UTC, anjula-sack commented
@RandilaP Please resolve the conflict here

2023-08-15 10:01 UTC, Piumal1999 commented
Hi @RandilaP @anjula-sack, 
I have already configured the dependency caching feature within pull request #1305. If this pull request is merged before mine, I will revert the changes made in my pull request.

2023-08-16 13:08 UTC, anjula-sack commented
I merged the pull request https://github.com/openmrs/openmrs-esm-patient-chart/pull/1305 this is no longer needed

2023-08-16 13:08 UTC, closed without merging