(fix)O3-2158:Clear order basket search input and trap focus when search gets reset
openmrs/openmrs-esm-patient-chart pull request #1210
Opened 2023-06-11 09:40 UTC by NYESIGA

## Requirements

- [ ] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://zeroheight.com/23a080e38/p/880723-introduction).
- [ ] My work includes tests or is validated by existing tests.

## Summary

## Screenshots

## Related Issue

## Other

2023-06-11 09:44 UTC, NYESIGA commented
Ticket https://issues.openmrs.org/browse/O3-2158

2023-06-11 10:21 UTC, jwnasambu commented
@NYESIGA this is a good progress! Kindly include a the description of what you changed and also a screenshot or video of the out put to confirm you have fixed the issue.

2023-06-11 11:29 UTC, NYESIGA commented
@jwnasambu  you check my changes

2023-06-12 06:09 UTC, Denywiryk commented
This is so far so good  for the intended results , but what could be causing the tests to fail ...?

2023-06-12 07:38 UTC, vasharma05 requested changes

2023-06-12 07:38 UTC, vasharma05 commented on packages/esm-patient-medications-app/src/order-basket/order-basket-search/order-basket-search-results.component.tsx
> +    }
This code block can be moved to the handleClick function above instead of setting a state and then running the useEffect

2023-06-12 07:38 UTC, vasharma05 commented on packages/esm-patient-medications-app/src/order-basket/order-basket-search/order-basket-search-results.component.tsx
> +
Why are these added?

2023-06-12 07:38 UTC, vasharma05 commented on packages/esm-patient-medications-app/src/order-basket/order-basket-search/order-basket-search-results.component.tsx
> +    }
```suggestion
  function handleClearSearchInput() {
    setSearchTerm('');
    searchInputRef.current.focus();
    }
```

2023-06-12 07:38 UTC, vasharma05 commented on packages/esm-patient-medications-app/src/order-basket/order-basket-search/order-basket-search-results.component.tsx
>  export default function OrderBasketSearchResults({
Don't pass the ref inside another component if the ref is not required.

Instead create a function
```
function focusOnSearchInput() {
  ref.current.focus()
}
```
and then pass this function in as a prop, which can then be called in the handleClick.

2023-06-12 07:39 UTC, vasharma05 commented on packages/esm-patient-medications-app/src/order-basket/order-basket-search/order-basket-search-results.component.tsx
>  export default function OrderBasketSearchResults({
For passing refs, please refer: https://react.dev/reference/react/forwardRef

2023-06-13 10:09 UTC, vasharma05 commented
Hi @NYESIGA !
I've left some comments above for improvements.
Please go through them

2023-06-13 11:29 UTC, NYESIGA commented
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0cm;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:612.0pt 792.0pt;
	margin:72.0pt 72.0pt 72.0pt 72.0pt;}
div.WordSection1
	{page:WordSection1;}
-->I have made change according can have a look at them From: Vineet SharmaSent: 13 June 2023 13:10To: openmrs/openmrs-esm-patient-chartCc: NYESIGA; MentionSubject: Re: [openmrs/openmrs-esm-patient-chart] (fix)O3-2158:Clear order basket search input and trap focus when search gets reset (PR #1210) Hi @NYESIGA !I've left some comments above for improvements.Please go through them—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***> 

2023-06-13 17:41 UTC, vasharma05 commented on packages/esm-patient-medications-app/src/order-basket/order-basket-search/order-basket-search-results.component.tsx
> +    setIsSearchInputCleared(true);
What is the use for this state?

2023-06-13 17:42 UTC, vasharma05 commented on packages/esm-patient-medications-app/src/order-basket/order-basket-search/order-basket-search-results.component.tsx
> +    handleClearSearchInput();
This function is doing what the above 2 lines are doing
Duplication of code
You can delete this function altogether

2023-07-03 08:08 UTC, denniskigen commented
Any updates on this one? @vasharma05

2023-07-20 09:26 UTC, denniskigen commented
Closing to allow @jwnasambu to pick this up.

2023-08-20 12:56 UTC, closed without merging