(test)O3-2111: Add patient chart add program e2e test
openmrs/openmrs-esm-patient-chart pull request #1251
Opened 2023-07-01 16:55 UTC by RandilaP

## Requirements

- [ ] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://zeroheight.com/23a080e38/p/880723-introduction).
- [ ] My work includes tests or is validated by existing tests.

## Summary
Goal of this PR is to add a e2e test of add program function.

## Screenshots
<img width="1680" alt="image" src="https://github.com/openmrs/openmrs-esm-patient-chart/assets/106733522/f2a2bc2c-b379-447f-b2f4-ba74e4abe15f">

## Related Issue

https://issues.openmrs.org/browse/O3-2111

## Other

2023-07-01 16:57 UTC, RandilaP commented
Hey guys. Could you please take a look at this? I need some help with adding a data test id and I like to ask your opinion about what I'm missing @anjula-sack @Piumal1999 @jayasanka-sack

2023-07-08 11:50 UTC, anjula-sack requested changes

2023-07-08 11:50 UTC, anjula-sack commented on e2e/specs/add-program.spec.ts
> +});
```suggestion
});

```

2023-07-08 11:50 UTC, anjula-sack commented on e2e/specs/add-program.spec.ts
> +});
```suggestion
});

```

2023-07-08 11:50 UTC, anjula-sack commented on packages/esm-patient-programs-app/src/programs/programs-overview.component.tsx
> +                <TableBody data-testid="playwright1">
Let's remove the unwanted test ids @RandilaP

2023-07-17 08:50 UTC, RandilaP commented
@jayasanka-sack @anjula-sack @Piumal1999 I updated this PR with the current requirements that you asked for in previous PRs. I couldn't test this in the local server because of the issues with the form. But I tested this using the dev server. After testing it I added test ids and used them. I also locate each cells like in the allergies PR. I updated this test in to add a program and edit a program as @anjula requested

2023-07-17 15:30 UTC, anjula-sack commented on packages/esm-patient-programs-app/src/programs/programs-detailed-summary.component.tsx
> +                      <TableCell className="cds--table-column-menu" data-testid={'button'}>
Is this required? @RandilaP

2023-08-13 18:51 UTC, RandilaP commented
@jayasanka-sack Could you please review this

2023-08-14 03:14 UTC, anjula-sack requested changes

2023-08-14 03:14 UTC, anjula-sack commented on e2e/specs/add-and-edit-program.spec.ts
> +  const LocationCell = row.locator('td:nth-child(2)');
```suggestion
  const locationCell = row.locator('td:nth-child(2)');
```

2023-08-16 13:05 UTC, anjula-sack approved these changes
Good job! @RandilaP

2023-08-16 13:05 UTC, merged