(test) O3-2112:Add Add notes e2e test
openmrs/openmrs-esm-patient-chart pull request #1255
Opened 2023-07-03 13:36 UTC by RandilaP

## Requirements

- [ ] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://zeroheight.com/23a080e38/p/880723-introduction).
- [ ] My work includes tests or is validated by existing tests.

## Summary
Goal of this PR is to adding a add notes e2e test to patient chart repository

## Screenshots

## Related Issue

https://issues.openmrs.org/browse/O3-2112

## Other

2023-07-17 11:11 UTC, Piumal1999 requested changes

2023-07-17 11:11 UTC, Piumal1999 commented on e2e/specs/add-note.spec.ts
> +  await test.step('When I visit the notes page', async () => {
@RandilaP, We might need to update the gherkin syntax keywords of theses steps. Please refer to [this tutorial](https://www.guru99.com/gherkin-test-cucumber.html#4). 

Here's a small overview of how to use the Gherkin keywords:
<img width="760" alt="image" src="https://github.com/openmrs/openmrs-esm-patient-chart/assets/27498587/d54ff7b6-9906-4ae5-91b6-65000f006a93">

2023-07-17 11:11 UTC, Piumal1999 commented on e2e/specs/add-note.spec.ts
> +  await test.step('When I visit the notes page', async () => {
We use the "And" keyword when 2 or more consecutive steps with the same starting word come up.

Example:
```
When I input the email address
When I input the correct password
```

The above can be replaced with:
```
When I input the email address
And I input the correct password
```

2023-07-17 11:11 UTC, Piumal1999 commented on e2e/specs/add-note.spec.ts
> +    await notesPage.page.locator('#visitDateTimePicker').fill('03/07/2023');
Can we use 'getByLabel' or 'getByRole' functions for querying this (instead of using the id)?

2023-07-17 11:11 UTC, Piumal1999 commented on e2e/specs/add-note.spec.ts
> +    await notesPage.page.locator('#visitDateTimePicker').fill('03/07/2023');
Same for line 29,31,33

2023-08-17 04:26 UTC, RandilaP commented
@anjula-sack @Piumal1999 @jayasanka-sack Hey guys @ibacher said that this feature intentionally removed and we don't need this test anymore. So can I close this PR then?

2023-08-17 11:59 UTC, anjula-sack commented
> @anjula-sack @Piumal1999 @jayasanka-sack Hey guys @ibacher said that this feature intentionally removed and we don't need this test anymore. So can I close this PR then?

sure. can you link the slack thread here and close this. @RandilaP

2023-08-18 17:10 UTC, RandilaP commented
https://openmrs.slack.com/archives/C02UNMKFH8V/p1692206732465129

2023-08-18 17:10 UTC, RandilaP commented
https://openmrs.slack.com/archives/C02UNMKFH8V/p1692206732465129

2023-08-18 17:10 UTC, closed without merging