(feat) Migrating allergy form to RHF and Zod
openmrs/openmrs-esm-patient-chart pull request #1308
Opened 2023-08-13 12:59 UTC by lumuchris256

## Requirements

- [ ] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://zeroheight.com/23a080e38/p/880723-introduction).
- [ ] My work includes tests or is validated by existing tests.

## Summary

## Screenshots

## Related Issue

## Other

2023-08-24 08:31 UTC, hadijahkyampeire requested changes
@lumuchris256 I realized in your demo that the save and close button is always enabled but doesn't even save until all the filled are chosen, could you please disable it instead or add warning validations that tell the user that they need to complete the whole form.

2023-08-24 08:33 UTC, hadijahkyampeire commented on packages/esm-patient-allergies-app/src/allergies/allergies-form/allergy-form.test.tsx
> -    expect(screen.getByRole('button', { name: /save and close/i })).toBeDisabled();
If you fix what I mentioned above, then this test won't need to go away.

2023-08-27 09:44 UTC, lumuchris256 commented
reguested change
[Screencast from 2023-08-27 12-23-51.webm](https://github.com/openmrs/openmrs-esm-patient-chart/assets/59338693/03c824fc-195b-4f5a-a1c2-b33b105359cc)

2023-09-05 17:33 UTC, hadijahkyampeire submitted a review, later dismissed
Thanks @lumuchris256

2023-09-05 17:52 UTC, hadijahkyampeire commented
@lumuchris256 please fix the e2e tests, I see they are related to allergies.

2023-09-08 09:41 UTC, lumuchris256 commented
> @lumuchris256 please fix the e2e tests, I see they are related to allergies.

@hadijahkyampeire  the form is ready for your re-review

2023-09-08 14:11 UTC, denniskigen approved these changes
Thanks, @lumuchris256!

2023-09-08 14:13 UTC, merged