(feat) Migrating Vitals and Biometrics form to RHF and Zod
openmrs/openmrs-esm-patient-chart pull request #1310
Opened 2023-08-13 16:25 UTC by lumuchris256

## Requirements

- [ ] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://zeroheight.com/23a080e38/p/880723-introduction).
- [ ] My work includes tests or is validated by existing tests.

## Summary
Migrated the form to use reacthookform and zod 

## Screenshots

## Related Issue

## Other
cc @hadijahkyampeire @denniskigen

2023-08-23 11:31 UTC, hadijahkyampeire reviewed
Thanks @lumuchris256 , just wondering why you didn't validate single inputs, what happens if wrong values are input, does it throw any error or warning on the specific input.

2023-08-25 06:21 UTC, lumuchris256 commented
> > 
> 
> Validation is handled for every input 
> 
> ![vitalsvalidation](https://user-images.githubusercontent.com/59338693/263183492-5343f413-c206-4610-a510-9fde8b78a361.png)

2023-08-27 11:09 UTC, lumuchris256 commented
> Thanks @lumuchris256 , just wondering why you didn't validate single inputs, what happens if wrong values are input, does it throw any error or warning on the specific input.

Validations to single inputs are present ,needed some improvements 
chnages ready for re-review

[Screencast from 2023-08-27 13-52-05.webm](https://github.com/openmrs/openmrs-esm-patient-chart/assets/59338693/f8491d98-b5bc-43eb-8af0-42f6885bbf73)

2023-08-27 22:25 UTC, hadijahkyampeire commented on packages/esm-patient-vitals-app/src/vitals/vitals-biometrics-form/vitals-biometrics-form.test.tsx
> -    expect(mockSavePatientVitals).toHaveBeenCalledTimes(1);
Why did you remove these tests, we need to test that the form submits successfully.

2023-08-27 22:27 UTC, hadijahkyampeire requested changes
@lumuchris256 I am not sure why you removed most of the tests but we need them, Let me know why you you had to remove them.

2023-08-29 11:45 UTC, merged

2023-09-13 12:25 UTC, jayasanka-sack commented
@lumuchris256 @hadijahkyampeire I have to make the same comment as here: https://github.com/openmrs/openmrs-esm-patient-chart/pull/1278#issuecomment-1717498642