(enhc) Remove redundant translation configuration settings
openmrs/openmrs-esm-patient-chart pull request #1331
Opened 2023-08-27 11:32 UTC by donaldkibet

## Requirements

- [ ] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://zeroheight.com/23a080e38/p/880723-introduction).
- [ ] My work includes tests or is validated by existing tests.

## Summary
Remove redundant translation configuration settings

## Screenshots

## Related Issue

## Other

2023-08-27 17:39 UTC, vasharma05 approved these changes

2023-08-28 05:01 UTC, denniskigen commented
Thanks, @donaldkibet. Don't forget to update your config appropriately.

2023-08-28 07:31 UTC, jayasanka-sack commented
@donaldkibet It seems the server is throwing `503`s when performing some actions. Could you please look into it and let us know whether it is something related to your changes or a bug on the product itself? 

Instructions on how to check the test report can be found here: https://github.com/openmrs/openmrs-esm-patient-chart/tree/main/e2e#open-reports-from-github-actions--bamboo



<img width="1131" alt="image" src="https://github.com/openmrs/openmrs-esm-patient-chart/assets/33048395/58939a5c-5889-4745-88e1-78b9decbfb87">

2023-08-28 07:31 UTC, jayasanka-sack requested changes
@donaldkibet It seems the server is throwing `503`s when performing some actions. Could you please look into it and let us know whether it is something related to your changes or a bug on the product itself? 

Instructions on how to check the test report can be found here: https://github.com/openmrs/openmrs-esm-patient-chart/tree/main/e2e#open-reports-from-github-actions--bamboo



<img width="1131" alt="image" src="https://github.com/openmrs/openmrs-esm-patient-chart/assets/33048395/58939a5c-5889-4745-88e1-78b9decbfb87">

2023-08-28 15:12 UTC, donaldkibet commented
@jayasanka-sack looking into the issue, where the e2e test are failing is un-related to the changes that I have made.

2023-09-07 07:50 UTC, CynthiaKamau approved these changes

2023-09-07 07:56 UTC, vasharma05 commented on packages/esm-patient-chart-app/src/visit/start-visit-button.component.tsx
> -  const { startVisitLabel } = useConfig();
Can we also remove the `startVisitLabel` point from config as well?
Thanks!

2023-09-07 12:35 UTC, merged