(fix) Fix broken styles in visits widget
openmrs/openmrs-esm-patient-chart pull request #1398
Opened 2023-10-05 13:38 UTC by CynthiaKamau

## Requirements

- [ ] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://zeroheight.com/23a080e38/p/880723-introduction).
- [ ] My work includes tests or is validated by existing tests.

## Summary

Fix broken styles in visits widget

## Screenshots

https://www.loom.com/share/0cdc45d67a0943e296558edf53a7f5f2?sid=c2fb0955-8fac-413e-86bb-27a229c38457

## Related Issue

## Other

2023-10-05 13:58 UTC, donaldkibet requested changes

2023-10-05 13:58 UTC, donaldkibet commented on packages/esm-patient-chart-app/src/visit/visits-widget/past-visits-components/visit-summary.scss
> +    min-height: 8rem;
```suggestion
    min-height: spacing.$spacing-08;
```

2023-10-05 13:58 UTC, donaldkibet commented on packages/esm-patient-chart-app/src/visit/visits-widget/past-visits-components/visit-summary.scss
> +    outline: 3px solid var(--brand-03) !important;
```suggestion
    outline: spacing.$spacing-03 solid var(--brand-03) !important;
```

2023-10-05 13:58 UTC, donaldkibet commented on packages/esm-patient-chart-app/src/visit/visits-widget/past-visits-components/visit-summary.scss
> +    border-left: 3px solid $ui-03;
```suggestion
    border-left: spacing.$spacing-03 solid $ui-03;
```

2023-10-05 14:47 UTC, CynthiaKamau commented on packages/esm-patient-chart-app/src/visit/visits-widget/past-visits-components/visit-summary.scss
> +    outline: 3px solid var(--brand-03) !important;
`spacing.$spacing-03` is 8px

2023-10-06 13:58 UTC, donaldkibet approved these changes

2023-10-06 13:59 UTC, merged