Attachments - Added configuration to the allowed file extension.
openmrs/openmrs-esm-patient-chart pull request #1584
Opened 2024-01-15 13:39 UTC by icrc-loliveira

## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [x] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://zeroheight.com/23a080e38/p/880723-introduction).
- [x] My work includes tests or is validated by existing tests.

## Summary
This PR created a new configuration 'allowedExtensions' that allow filter by the extensions that can be attached to openMRS.

## Screenshots
![image](https://github.com/openmrs/openmrs-esm-patient-chart/assets/68058940/3c0f9302-2bec-4251-a022-aa89e694cc7a)
![image](https://github.com/openmrs/openmrs-esm-patient-chart/assets/68058940/08b7de8a-8cd5-4c22-94d5-2c66bcb9534c)

2024-01-17 11:09 UTC, icrc-loliveira commented
@ibacher

2024-01-17 17:06 UTC, ibacher requested changes
Thanks @icrc-loliveira!

2024-01-17 17:06 UTC, ibacher commented on packages/esm-patient-attachments-app/src/attachments/use-allowed-extensions.ts
> +  const customRepresentation = 'custom:(uuid,property,value,description)';
Do we need the description?

2024-01-17 17:06 UTC, ibacher commented on packages/esm-patient-attachments-app/src/attachments/use-allowed-extensions.ts
> +      ? data?.data?.results[0].value?.split(',').map<string>((ext) => (ext = '.' + ext))
```suggestion
      ? data?.data?.results[0].value?.split(',').map((ext) => '.' + ext)
```

2024-01-17 17:06 UTC, ibacher commented on packages/esm-patient-attachments-app/src/attachments/use-allowed-extensions.ts
> +  const extensions: Array<string> =
Why do we have this if it's never returned or used?

2024-01-17 17:06 UTC, ibacher commented on packages/esm-patient-attachments-app/src/camera-media-uploader/media-uploader.component.tsx
> +          accept={allowedExtensions?.map<string>((ext) => (ext = '.' + ext)) ?? ['*']}
```suggestion
          accept={allowedExtensions?.map((ext) =>  '.' + ext) || ['*']}
```

2024-01-17 17:06 UTC, ibacher commented on packages/esm-patient-attachments-app/src/constants.ts
> +export const allowedExtensionsGlobalProperty: string = 'attachments.allowedFileExtensions';
I don't think we need a constants file unless this is used in multiple places. Just keep this local to the hook that uses it.

2024-01-29 16:21 UTC, ibacher requested changes
Couple of small things. Has this been tested in a system without that global property set?

2024-01-29 16:21 UTC, ibacher commented on packages/esm-patient-attachments-app/src/attachments/attachments-overview.component.tsx
> +import { List, Thumbnail_2, Add } from '@carbon/react/icons';
This should still be up around line 3

2024-01-29 16:21 UTC, ibacher commented on packages/esm-patient-attachments-app/src/attachments/use-allowed-extensions.ts
> +  const customRepresentation = 'custom:(uuid,property,value)';
```suggestion
  const customRepresentation = 'custom:(value)';
```

2024-01-29 16:21 UTC, ibacher commented on packages/esm-patient-attachments-app/src/attachments/use-allowed-extensions.ts
> +  const customRepresentation = 'custom:(uuid,property,value)';
We only really need the value right?

2024-01-29 16:21 UTC, ibacher commented on packages/esm-patient-attachments-app/src/attachments/use-allowed-extensions.ts
> +    allowedExtensions: data?.data?.results?.length > 0 ? data?.data?.results[0].value?.split(',') : undefined,
Deal with an empty string:

```suggestion
    allowedExtensions: data?.data?.results?.length > 0 ? data?.data?.results[0].value?.split(',') || undefined : undefined,
```

2024-01-30 18:16 UTC, ibacher approved these changes

2024-01-30 18:17 UTC, merged