(feat) O3-2163: Add support for editing end visit data/time on current visits
openmrs/openmrs-esm-patient-chart pull request #1712
Opened 2024-03-04 19:41 UTC by usamaidrsk

## Requirements

- [ ] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://zeroheight.com/23a080e38/p/880723-introduction).
- [ ] My work includes tests or is validated by existing tests.

## Summary

This PR provisions the adding of end date to current visits

## Screenshots

Uploading add-end-visit-field-on-edit-visit-.mp4…

## Related Issue

[O3-2163](https://openmrs.atlassian.net/browse/O3-2163)

## Other

2024-06-28 19:17 UTC, brandones requested changes
Thanks for this, @usamaidrsk . Can you confirm that the start visit validator on lines 151-154 make sense? I don't really understand why if there is an existing visit then it's fine if the start date is in the future.

```jsx
        (value) => {
          const today = dayjs();
          const startDate = dayjs(value);
          return displayVisitStopDateTimeFields ? true : startDate.isSameOrBefore(today, 'day');
        },
```

Please add unit tests for the end date behavior. The logic of how we decide to show these fields or not is a little funny, so it would be very good to make the intention explicit in tests.

2024-07-19 09:39 UTC, denniskigen commented
@vasharma05 @usamaidrsk could you guys sync up to figure out how to move this forward?

2024-08-19 16:00 UTC, brandones commented
Ping @usamaidrsk @vasharma05

2024-09-15 10:54 UTC, brandones commented
Ping @usamaidrsk

2024-10-21 18:40 UTC, brandones requested changes
Looks like we have a failing E2E test, and it is being caused by this work. Please fix the E2E test.

2024-11-03 23:26 UTC, brandones commented on packages/esm-patient-chart-app/src/visit/visit-form/visit-form.component.tsx
> +            : z.string().optional(),
Should this optional one also have the `refine` clause?

2024-11-04 15:57 UTC, brandones approved these changes

2024-11-04 15:57 UTC, merged