(test) O3-2943: Edit e2e test for the immunization recording workflow
openmrs/openmrs-esm-patient-chart pull request #1768
Opened 2024-03-31 16:52 UTC by Vijaykv5

## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing.en-US#contributing-guidelines) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://om.rs/o3ui).
- [x] My work includes tests or is validated by existing tests.

## Summary

This PR introduces changes that edits E2E test for recording an immunization

## Related Issue

[O3-2943](https://openmrs.atlassian.net/browse/O3-2943)

## Other

2024-03-31 16:55 UTC, Vijaykv5 commented
Kindly can you review this PR
@kdaud

2024-04-01 09:35 UTC, kdaud commented
@Vijaykv5 did you take a look at the logs?

2024-04-05 18:34 UTC, denniskigen commented
Here's the playwright report:

[playwright-report (2).zip](https://github.com/openmrs/openmrs-esm-patient-chart/files/14889481/playwright-report.2.zip)

Looks like the test is failing because there are no immunizations to edit. Maybe you need to combine the two specs.

2024-04-05 18:36 UTC, Vijaykv5 commented
> @Vijaykv5 did you take a look at the logs?

Yes @kdaud
I'm not able to figure out, the test is failing here:
`await page.click('[aria-label="Expand current row"]');`

2024-04-05 18:40 UTC, Vijaykv5 commented
but @denniskigen we are separating each functions right?
add, edit and cancel immunization.  [#comment](https://github.com/openmrs/openmrs-esm-patient-chart/pull/1664#discussion_r1516246308)

2024-04-05 18:41 UTC, denniskigen commented
I defer to @jayasanka-sack for the ideal approach.

2024-04-22 06:54 UTC, jayasanka-sack commented
@Vijaykv5 

Check line 10. When the edit test runs, it fails because it's using a brand-new patient with no existing data. We could switch to using `beforeAll` to avoid this, but then the edit test would depend on the create test, and we want to keep them separate.

A good fix would be to create an immunization record at the start of the edit test using the REST API. That should provide the necessary data for the test to work properly.

Lemme know if you have any questions! :)

2024-04-22 12:11 UTC, Vijaykv5 commented
> @Vijaykv5
> 
> Check line 10. When the edit test runs, it fails because it's using a brand-new patient with no existing data. We could switch to using `beforeAll` to avoid this, but then the edit test would depend on the create test, and we want to keep them separate.
> 
> A good fix would be to create an immunization record at the start of the edit test using the REST API. That should provide the necessary data for the test to work properly.
> 
> Lemme know if you have any questions! :)



@jayasanka-sack So do I need to call this [API](https://github.com/openmrs/openmrs-esm-patient-chart/blob/main/packages/esm-patient-immunizations-app/src/immunizations/immunizations.resource.tsx)  inside [commands](https://github.com/openmrs/openmrs-esm-patient-chart/blob/main/e2e/commands/visit-operations.ts#L31) or I may need to create a separate file for creating immunization record using the REST API?

2024-04-24 07:35 UTC, jayasanka-sack commented
> @jayasanka-sack So do I need to call this [API](https://github.com/openmrs/openmrs-esm-patient-chart/blob/main/packages/esm-patient-immunizations-app/src/immunizations/immunizations.resource.tsx) inside [commands](https://github.com/openmrs/openmrs-esm-patient-chart/blob/main/e2e/commands/visit-operations.ts#L31) or I may need to create a separate file for creating immunization record using the REST API?

@Vijaykv5 Write a command and call it within the edit test.

2024-05-24 12:00 UTC, denniskigen commented
@jayasanka-sack could you please help Vijay get this over the line?

2024-06-10 13:55 UTC, jayasanka-sack commented
@Vijaykv5 Follow these steps:

1. In `e2e/fixtures/api.ts`, update the base url of the API fixture to ` ${process.env.E2E_BASE_URL}/ws`. So that we can invoke fhir endpoints
2. Update existing API calls to use `/rest/` prefix. ex: `const patientRes = await api.post('/rest/patient', {` 
3. Create a new function under `patient-operations.ts` file to create an immunization.
    You should send a post request to the following endpoint with the given payload (feel free to edit).
   `/fhir2/R4/Immunization?_summary=data`
    
    ```
       {
        "resourceType": "Immunization",
        "status": "completed",
        "vaccineCode": {
          "coding": [
            {
              "code": "783AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
              "display": "Polio vaccination, oral"
            }
          ]
        },
        "patient": {
          "type": "Patient",
          "reference": "Patient/703840a5-7339-4dc2-8993-f7cc7b96fc94"
        },
        "encounter": {
          "type": "Encounter",
          "reference": "Encounter/fca94b00-8b1f-4468-b006-68e77f438978"
        },
        "occurrenceDateTime": "2024-06-10T13:50:00.000Z",
        "expirationDate": "2052-06-29T18:30:00.000Z",
        "location": {
          "type": "Location",
          "reference": "Location/44c3efb0-2583-4c80-a79e-1f756a03c0a1"
        },
        "performer": [
          {
            "actor": {
              "type": "Practitioner",
              "reference": "Practitioner/f39e57d8-1185-4199-8567-6f1eeb160f05"
            }
          }
        ],
        "manufacturer": {
          "display": " Sanofi Pasteur SA"
        },
        "lotNumber": "POLIO-001",
        "protocolApplied": [
          {
            "doseNumberPositiveInt": 1,
            "series": null
          }
        ]
      }
    ```
 4. Create a new spec file for the edit immunization
 5. Call the created function from the `beforeEach` hook of the test.

2024-06-10 13:55 UTC, jayasanka-sack requested changes
@Vijaykv5 Follow these steps:

In e2e/fixtures/api.ts, update the base url of the API fixture to  ${process.env.E2E_BASE_URL}/ws. So that we can invoke fhir endpoints

Update existing API calls to use /rest/ prefix. ex: const patientRes = await api.post('/rest/patient', {

Create a new function under patient-operations.ts file to create an immunization.
You should send a post request to the following endpoint with the given payload (feel free to edit).
/fhir2/R4/Immunization?_summary=data

   {
    "resourceType": "Immunization",
    "status": "completed",
    "vaccineCode": {
      "coding": [
        {
          "code": "783AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
          "display": "Polio vaccination, oral"
        }
      ]
    },
    "patient": {
      "type": "Patient",
      "reference": "Patient/703840a5-7339-4dc2-8993-f7cc7b96fc94"
    },
    "encounter": {
      "type": "Encounter",
      "reference": "Encounter/fca94b00-8b1f-4468-b006-68e77f438978"
    },
    "occurrenceDateTime": "2024-06-10T13:50:00.000Z",
    "expirationDate": "2052-06-29T18:30:00.000Z",
    "location": {
      "type": "Location",
      "reference": "Location/44c3efb0-2583-4c80-a79e-1f756a03c0a1"
    },
    "performer": [
      {
        "actor": {
          "type": "Practitioner",
          "reference": "Practitioner/f39e57d8-1185-4199-8567-6f1eeb160f05"
        }
      }
    ],
    "manufacturer": {
      "display": " Sanofi Pasteur SA"
    },
    "lotNumber": "POLIO-001",
    "protocolApplied": [
      {
        "doseNumberPositiveInt": 1,
        "series": null
      }
    ]
  }
Create a new spec file for the edit immunization

Call the created function from the beforeEach hook of the test.

2024-06-24 13:23 UTC, Vijaykv5 commented
@jayasanka-sack The PR now work fine in locally with the help of [`Immunization data`](https://github.com/openmrs/openmrs-esm-patient-chart/pull/1768/files#diff-2c978d5b549cacbac1f3e2b08e2e9a4003638a0883895adbd02f9cfa3d8c1b18R109) but It fails in E2E Tests .
Any possible reason for this?

2024-07-23 15:33 UTC, brandones commented
Hi @Vijaykv5 , are you still available to work on this? You need to be able to debug test failures on your own. Especially if they are as straightforward as the one here.

2024-07-26 07:02 UTC, Vijaykv5 commented
Sorry @brandones I was pinned with some other tickets.

Will soon fix this up!

2024-07-26 13:41 UTC, jayasanka-sack commented
I tested this locally with Docker and dev3 and it works fine. It only fails when running on GitHub Actions. I'm not sure why. This is the request and the response. @ibacher @mogoodrich @mseaton @mherman22 any idea what this error message means?

Request:

```json
{
  "resourceType": "Immunization",
  "status": "completed",
  "vaccineCode": {
    "coding": [
      {
        "code": "783AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
        "display": "Hepatitis B vaccination"
      }
    ]
  },
  "patient": {
    "type": "Patient",
    "reference": "Patient/abd466a2-b4cc-4290-901c-5444c96662f0"
  },
  "encounter": {
    "type": "Encounter",
    "reference": "Encounter/a394aaa2-d9ef-42bd-9abc-813d91a68423"
  },
  "occurrenceDateTime": "2024-06-10T13:50:00.000Z",
  "expirationDate": "2052-06-29T18:30:00.000Z",
  "location": {
    "type": "Location",
    "reference": "Location/44c3efb0-2583-4c80-a79e-1f756a03c0a1"
  },
  "performer": [
    {
      "actor": {
        "type": "Practitioner",
        "reference": "Practitioner/f39e57d8-1185-4199-8567-6f1eeb160f05"
      }
    }
  ],
  "manufacturer": {
    "display": "Sanofi Pasteur SA"
  },
  "lotNumber": "POLIO-001",
  "protocolApplied": [
    {
      "doseNumberPositiveInt": 1,
      "series": null
    }
  ]
}
```
Response:
```json
{
  "resourceType": "OperationOutcome",
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><h1>Operation Outcome</h1><table border=\"0\"><tr><td style=\"font-weight: bold;\">ERROR</td><td>[]</td><td><pre>The Immunization resource is required to be attached to an OpenMRS encounter involving a single encounter provider with the role 'Clinician'. This is not the case for immunization '5f109c97-9f6f-4330-bb9f-a29d1d18fad9' attached to encounter 'f647ef65-07e6-42ff-9e1c-cb6e45f8ed3d'.</pre></td>\n\t\t\t</tr>\n\t\t</table>\n\t</div>"
  },
  "issue": [
    {
      "severity": "error",
      "code": "business-rule",
      "diagnostics": "The Immunization resource is required to be attached to an OpenMRS encounter involving a single encounter provider with the role 'Clinician'. This is not the case for immunization '5f109c97-9f6f-4330-bb9f-a29d1d18fad9' attached to encounter 'f647ef65-07e6-42ff-9e1c-cb6e45f8ed3d'."
    }
  ]
}
```

2024-07-26 20:10 UTC, mherman22 commented
> I tested this locally with Docker and dev3 and it works fine. It only fails when running on GitHub Actions. I'm not sure why. This is the request and the response. @ibacher @mogoodrich @mseaton @mherman22 any idea what this error message means?
> 
> Request:
> 
> ```json
> {
>   "resourceType": "Immunization",
>   "status": "completed",
>   "vaccineCode": {
>     "coding": [
>       {
>         "code": "783AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
>         "display": "Hepatitis B vaccination"
>       }
>     ]
>   },
>   "patient": {
>     "type": "Patient",
>     "reference": "Patient/abd466a2-b4cc-4290-901c-5444c96662f0"
>   },
>   "encounter": {
>     "type": "Encounter",
>     "reference": "Encounter/a394aaa2-d9ef-42bd-9abc-813d91a68423"
>   },
>   "occurrenceDateTime": "2024-06-10T13:50:00.000Z",
>   "expirationDate": "2052-06-29T18:30:00.000Z",
>   "location": {
>     "type": "Location",
>     "reference": "Location/44c3efb0-2583-4c80-a79e-1f756a03c0a1"
>   },
>   "performer": [
>     {
>       "actor": {
>         "type": "Practitioner",
>         "reference": "Practitioner/f39e57d8-1185-4199-8567-6f1eeb160f05"
>       }
>     }
>   ],
>   "manufacturer": {
>     "display": "Sanofi Pasteur SA"
>   },
>   "lotNumber": "POLIO-001",
>   "protocolApplied": [
>     {
>       "doseNumberPositiveInt": 1,
>       "series": null
>     }
>   ]
> }
> ```
> 
> Response:
> 
> ```json
> {
>   "resourceType": "OperationOutcome",
>   "text": {
>     "status": "generated",
>     "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><h1>Operation Outcome</h1><table border=\"0\"><tr><td style=\"font-weight: bold;\">ERROR</td><td>[]</td><td><pre>The Immunization resource is required to be attached to an OpenMRS encounter involving a single encounter provider with the role 'Clinician'. This is not the case for immunization '5f109c97-9f6f-4330-bb9f-a29d1d18fad9' attached to encounter 'f647ef65-07e6-42ff-9e1c-cb6e45f8ed3d'.</pre></td>\n\t\t\t</tr>\n\t\t</table>\n\t</div>"
>   },
>   "issue": [
>     {
>       "severity": "error",
>       "code": "business-rule",
>       "diagnostics": "The Immunization resource is required to be attached to an OpenMRS encounter involving a single encounter provider with the role 'Clinician'. This is not the case for immunization '5f109c97-9f6f-4330-bb9f-a29d1d18fad9' attached to encounter 'f647ef65-07e6-42ff-9e1c-cb6e45f8ed3d'."
>     }
>   ]
> }
> ```

Not sure if this answers you but all it is saying here is that the immunization resource you are creating which is attached to the encounter above doesn't involve an encounter provider with the role 'Clinician' so i think you might need to create a visit then an encounter then encounter provider in that order -> see this https://github.com/openmrs/openmrs-module-fhir2/blob/de31a6838324ba2546b6eb71a69cdd77f36aa168/test-data/src/main/resources/org/openmrs/module/fhir2/api/dao/impl/FhirImmunizationDaoImplTest_initial_data.xml#L28-L36

2024-08-19 16:15 UTC, brandones commented
@jayasanka-sack Well, the error is being produced by OpenMRS business logic, so it's not anything weird about how GitHub Actions works. There's probably just some difference between that server's setup and dev3 and the Docker setup. Maybe the user doesn't have the Clinician role, or maybe some UUIDs are different, or maybe the encounter isn't getting created the same way.

2024-08-20 18:09 UTC, ibacher commented
The encounter should be an _encounter_ and not a visit. I _think_ it can be left blank. Granted that's probably less than ideal.

2024-08-23 16:57 UTC, jayasanka-sack commented
> The encounter should be an _encounter_ and not a visit. I _think_ it can be left blank. Granted that's probably less than ideal.

Ohhh that's the issue! @Vijaykv5 could you please fix this?

2024-08-23 16:59 UTC, ibacher commented
We should probably ticket this for the FHIR2 module, though. It should be possible to specify a visit and just create the encounter if required.

2024-09-15 10:37 UTC, brandones commented
Ping @Vijaykv5

2024-10-10 16:29 UTC, brandones commented
Ping @Vijaykv5 , CC @jayasanka-sack

2024-10-20 05:11 UTC, Vijaykv5 commented
@jayasanka-sack @denniskigen may you could help me with creating an order encounter to get the encounter ID?
I've been trying to follow [this](https://rest.openmrs.org/#create-an-encounter-type), but found it difficult

2024-11-14 11:46 UTC, jayasanka-sack commented on e2e/commands/patient-operations.ts
> +          reference: 'Practitioner/f39e57d8-1185-4199-8567-6f1eeb160f05',
I had a chat with Ian, and it has nothing to do with the encounter but we suspect this is what causing issue as this UUID doesn't exist. Let me update the PR. 

These are the valid values: https://github.com/openmrs/openmrs-module-referencedemodata/blob/2.x/api/src/main/java/org/openmrs/module/referencedemodata/ReferenceDemoDataConstants.java

2025-04-23 07:51 UTC, denniskigen commented
Closing as stale.

2025-04-23 07:51 UTC, closed without merging