(feat) O3-3174: Move visit related tags into the Visit Header component.
openmrs/openmrs-esm-patient-chart pull request #1870
Opened 2024-06-18 12:16 UTC by Twiineenock

## Requirements

- [ ] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing.en-US#contributing-guidelines) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://om.rs/o3ui).
- [ ] My work includes tests or is validated by existing tests.

## Summary

With this PR, the visit note tag and other visit related tags are moved to the visit header component as suggested by [paulsonder](https://github.com/paulsonder) in the ticket description here [https://openmrs.atlassian.net/browse/O3-3174](https://openmrs.atlassian.net/browse/O3-3174)

## Screenshots

## Related Issue

[https://openmrs.atlassian.net/browse/O3-3174](https://openmrs.atlassian.net/browse/O3-3174)

## Other

2024-08-15 11:50 UTC, denniskigen commented
FYI @ciaranduffy

2024-08-19 16:21 UTC, brandones requested changes

2024-08-19 16:21 UTC, brandones commented on packages/esm-patient-chart-app/src/visit-header/visit-header.component.tsx
> +      />
Is that class necessary? It seems like the right styles are being brought by the visit-attribute-tags component.

I would rather this slot be called `visit-header-middle-slot`. Better to be less opinionated about what goes in it. 

Maybe eventually we could put the stuff below, from queue entry, into the slot as extensions—the code below feels a bit out of place. But that's a different PR.

2024-09-15 10:58 UTC, brandones commented
Ping @Twiineenock . Is it clear to you how to move forward with this?

2024-10-21 19:07 UTC, brandones commented
Closing since @Twiineenock is unresponsive

2024-10-21 19:07 UTC, closed without merging