feat/O3-3846: All Calendar Date Pickers should use the same OpenmrsDatePicker component across entire EMR
openmrs/openmrs-esm-patient-chart pull request #2154
Opened 2024-12-13 14:22 UTC by jwnasambu

## Requirements

- [ ] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing.en-US#contributing-guidelines) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://om.rs/o3ui).
- [ ] My work includes tests or is validated by existing tests.

## Summary

## Screenshots

## Related Issue

https://openmrs.atlassian.net/browse/O3-3846

## Other

2024-12-13 16:46 UTC, ibacher commented on packages/esm-patient-chart-app/src/mark-patient-deceased/mark-patient-deceased-form.scss
> +.OpenmrsDatePicker {
We don't necessarily need to rename the classes...

2024-12-13 16:46 UTC, ibacher commented on packages/esm-patient-chart-app/src/visit/visit-form/visit-date-time.component.tsx
>                  value={value ? dayjs(value).format('DD/MM/YYYY') : null}
Oh! Don't do this. Just pass in the `value` directly.

2024-12-13 16:46 UTC, ibacher commented on packages/esm-patient-tests-app/src/test-results/print-modal/print-modal.extension.tsx
>                <DatePickerInput
Shouldn't have this

2024-12-16 17:25 UTC, NethmiRodrigo requested changes
Thanks @jwnasambu! Left a few nitpicks:

2024-12-16 18:23 UTC, ibacher commented on packages/esm-patient-orders-app/src/components/orders-details-table.component.tsx
> +        <OpenmrsDatePicker
Yeah, for right now we don't have a date range picker.

2024-12-18 21:06 UTC, ibacher commented on packages/esm-patient-tests-app/src/test-results/print-modal/print-modal.extension.tsx
> +  const [selectedFromDate] = useState(null);
You still need the setter here.

2024-12-18 21:06 UTC, ibacher commented on packages/esm-patient-tests-app/src/test-results/print-modal/print-modal.extension.tsx
> +              onChange={setSelectedToDate}
This should be calling `setSelectedFromDate()`, right?

2024-12-18 21:06 UTC, ibacher commented on packages/esm-patient-programs-app/src/programs/programs-form.workspace.tsx
> +            invalidText={errors?.selectedProgramStatus?.message}
Shouldn't this be `fieldState?.error?.message` like we were using previously?

2024-12-18 23:15 UTC, jwnasambu commented
@ibacher One thing I am picking from the error I am getting on this PR is `specificMockImpl.apply` is not a function.  I want to believe it occurs when a mocked function is not properly set up, or its implementation does not correctly replicate the original behavior of the function. In[ this case](https://github.com/openmrs/openmrs-esm-core/blob/fc95b353b7e38c6be5bc6be9aad6b3588005326c/packages/framework/esm-framework/mock.tsx#L66), OpenmrsDatePicker is being mocked using jest.fn(realOpenmrsDatePicker), which can be a problem if realOpenmrsDatePicker is either a class or a React component and not a function. It’s for that reason I am thinking Instead of using jest.fn(realOpenmrsDatePicker),  we mock it directly as a functional component? kindly what is your take?

2024-12-19 21:35 UTC, denniskigen commented
Try using this stub implementation of the `OpenmrsDatePicker` component to fix your tests:

```tsx
import { OpenmrsDatePicker } from '@openmrs/esm-framework';

const mockOpenmrsDatePicker = jest.mocked(OpenmrsDatePicker);

mockOpenmrsDatePicker.mockImplementation(({ id, labelText, value, onChange }) => {
  return (
    <>
      <label htmlFor={id}>{labelText}</label>
      <input
        aria-label={labelText.toString()}
        id={id}
        onChange={(evt) => {
          onChange(dayjs(evt.target.value).toDate());
        }}
        type="text"
        // @ts-ignore
        value={value ? dayjs(value).format('DD/MM/YYYY') : ''}
      />
    </>
  );
});
```

2024-12-25 11:16 UTC, Muppasanipraneeth commented
@jwnasambu  Standardize the use of the OpenMRS date picker Across All Apps [O3-4287](https://openmrs.atlassian.net/browse/O3-4287) however you are working on it . I checked  what are changes you made  . you already working on the visits, medication,conditions,Immunization,program,and other I think you did not worked on the Appointments so please  work on it also Thank you .

2025-01-07 12:42 UTC, denniskigen commented on packages/esm-patient-chart-app/src/mark-patient-deceased/mark-patient-deceased-form.workspace.tsx
>                        id="deceasedDate"
We need to maintain parity between the props passed to the Carbon datepicker and those passed to `OpenmrsDatePicker`. In this case, this implementation is missing several props including `labelText`, `isInvalid`, and `invalidText`. It should look like this instead:

```tsx
<OpenmrsDatePicker
    className={styles.datePicker}
    id="deceasedDate"
    isInvalid={!!errors?.deathDate}
    invalidText={errors?.deathDate?.message}
    labelText={t('dateOfDeath', 'Date of death')}
    maxDate={new Date().toISOString()}
    onChange={(date) => onChange(date)}
    value={value}
  />
```

2025-01-07 19:07 UTC, denniskigen commented
So I looked at the failing programs-form test and I couldn't exactly figure out why the test was failing to set the correct dates. In the interest of getting the tests passing, I think we could modify it as follows:

```tsx
describe('ProgramsForm', () => {
  const inpatientWardUuid = 'b1a8b05e-3542-4037-bbd3-998ee9c40574';
  const oncologyScreeningProgramUuid = '11b129ca-a5e7-4025-84bf-b92a173e20de';

  it('renders a success toast notification upon successfully recording a program enrollment', async () => {
    await user.type(enrollmentDateInput, '2020-05-05'); // remove this line so we rely on the default enrollment date
  });

  it('updates a program enrollment', async () => {
    const completionDateInput = screen.getByRole('textbox', { name: /date completed/i }); // remove this line and replace it with the next line
    const enrollmentLocationInput = screen.getByRole('combobox', { name: /enrollment location/i });

    // so we can simulate changing the enrollment location instead of the date

    // remove the next two lines
    await user.type(completionDateInput, '05/05/2020');
    await user.tab();

    // and replace them with the next two lines
    await user.click(enrollmentLocationInput);
    await user.selectOptions(enrollmentLocationInput, [inpatientWardUuid]);

    expect(mockUpdateProgramEnrollment).toHaveBeenCalledTimes(1);
    // and then check for this payload instead
    expect(mockUpdateProgramEnrollment).toHaveBeenCalledWith(
      mockEnrolledProgramsResponse[0].uuid,
      expect.objectContaining({
        dateCompleted: null,
        dateEnrolled: expect.stringMatching(/^2020-01-16/),
        location: mockLocationsResponse[1].uuid,
        patient: mockPatient.id,
        program: mockEnrolledProgramsResponse[0].program.uuid,
      }),
      new AbortController(),
    );
  });
};
```

2025-01-07 19:10 UTC, denniskigen commented
Another observation I made is that you'd need to add the `OpenmrsDatePicker` stub to the following tests to fix the `specificMockImpl.apply is not a function` error:

- `mark-patient-deceased-form.test.tsx`
- `visit-form.test.tsx`
- `conditions-form.test.tsx`
- `immunizations-form.test.tsx`
- `add-drug-order.test.tsx`
- `visit-notes-form.test.tsx`
- `order-details-table.test.tsx`
- `programs-form.test.tsx`

2025-01-07 19:11 UTC, jwnasambu commented
Thanks @denis I was somewhere I had reduced some build failures from 4 to one only that my adapter has blown off and I am planning to pick up from there tomorrow by God's grace when my issue is fixed.

Yahoo Mail: Search, Organize, Conquer 
 
  On Tue, Jan 7, 2025 at 10:11 PM, Dennis ***@***.***> wrote:   


Another observation I made is that you'd need to add the OpenmrsDatePicker stub to the following tests to fix the specificMockImpl.apply is not a function error:
   
   - mark-patient-deceased-form.test.tsx
   - visit-form.test.tsx
   - conditions-form.test.tsx
   - immunizations-form.test.tsx
   - add-drug-order.test.tsx
   - visit-notes-form.test.tsx
   - order-details-table.test.tsx
   - programs-form.test.tsx

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2025-01-15 21:27 UTC, denniskigen commented on packages/esm-patient-conditions-app/src/conditions/conditions-form.test.tsx
> +});
Additionally, we can remove the following lines:

```tsx 
  // line 167
  await user.type(onsetDateInput, '2020-05-05');

  // line 170 - 172
  await waitFor(() => {
  expect(mockShowSnackbar).toHaveBeenCalled();
  });
```

2025-01-16 17:18 UTC, NethmiRodrigo commented on packages/esm-patient-immunizations-app/src/immunizations/immunizations-form.workspace.tsx
> -                      dateFormat={datePickerFormat}
Please remove the `datePickerFormat` definition since its no longer required.

2025-01-16 21:12 UTC, jwnasambu commented on packages/esm-patient-immunizations-app/src/immunizations/immunizations-form.workspace.tsx
> -                      dateFormat={datePickerFormat}
@NethmiRodrigo, the changes you are requesting have already been fixed. Could I be missing out on something?

2025-01-16 21:59 UTC, denniskigen commented on packages/esm-patient-orders-app/src/components/order-details-table.test.tsx
> +});
```suggestion
```

https://o3-docs.openmrs.org/docs/frontend-modules/unit-and-integration-testing#you-should-not-need-to-use-partial-mocks

2025-01-17 06:17 UTC, NethmiRodrigo commented on packages/esm-patient-immunizations-app/src/immunizations/immunizations-form.workspace.tsx
> -                      dateFormat={datePickerFormat}
Yep, you're right! Sorry I missed that!

2025-01-30 19:39 UTC, ibacher commented
So I do think the E2E tests that are failing here need to be adjusted. They're unfortunately relying on some Carbon implementation details (including, e.g., having a specific id for the date input).

2025-02-14 07:35 UTC, vasharma05 commented
Now, I am officially tired of fixing the E2E tests repeatedly 😢

2025-02-18 10:42 UTC, rbuisson commented
Hi @ibacher , @denniskigen , any chance to get this merged?

2025-02-19 15:43 UTC, ibacher commented
@rbuisson It's in progress, but not yet fixed. This should be in for the 3.4.0 release (release after next).

2025-03-03 15:50 UTC, ibacher commented on packages/esm-patient-chart-app/src/visit/visit-form/visit-attribute-type.component.tsx
> +            aria-invalid={!!fieldState?.error?.message}
```suggestion
```

2025-03-03 15:52 UTC, ibacher commented on packages/esm-patient-chart-app/src/visit/visit-form/visit-date-time.component.tsx
>    const maxDateObj = maxDate ? dayjs(new Date(maxDate).setHours(23, 59, 59, 59)).format('DD/MM/YYYY') : null;
```suggestion
  const maxDateObj = maxDate ? dayjs(new Date(maxDate).setHours(23, 59, 59, 59)) : null;
```

2025-03-03 15:54 UTC, ibacher approved these changes

2025-03-06 09:37 UTC, NethmiRodrigo approved these changes

2025-03-06 09:38 UTC, merged

2025-03-06 09:39 UTC, NethmiRodrigo commented
Thanks @jwnasambu!