O3-4227: Write an E2E test for mark a patient as deceased
openmrs/openmrs-esm-patient-chart pull request #2156
Opened 2024-12-14 10:30 UTC by dilankavishka

## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing.en-US#contributing-guidelines) label. See existing PR titles for inspiration.
- [x] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://om.rs/o3ui).
- [x] My work includes tests or is validated by existing tests.

## Summary

This PR is need to write an E2E test for mark a patient as deceased.

## Screenshots

## Related Issue

https://openmrs.atlassian.net/browse/O3-4227

## Other

2024-12-14 10:31 UTC, dilankavishka commented
@jayasanka-sack @kdaud Can you review this please?

2024-12-16 07:26 UTC, jayasanka-sack commented
@dilankavishka The test is failing. You can download the report file to check what's causing it. Please fix it and make sure it passes locally.

2024-12-16 07:26 UTC, jayasanka-sack requested changes
@dilankavishka The test is failing. You can download the report file to check what's causing it. Please fix it and make sure it passes locally.

2024-12-16 07:30 UTC, jayasanka-sack requested changes

2024-12-16 07:30 UTC, jayasanka-sack commented on e2e/pages/mark-patient-deceased-page.ts
> +  }
No need to create new functions for these as keeping them in the spec file is clean enough. We only create functions if they're being used in multiple places.

2024-12-16 07:30 UTC, jayasanka-sack commented on e2e/specs/mark-patient-deceased.spec.ts
> +  });
Use the exact test steps from the ticket. Generic steps can be confusing since they don't show what information was filled in the form.

2025-01-06 14:18 UTC, dilankavishka commented
@jayasanka-sack , @denniskigen can you review this please?

2025-01-07 06:55 UTC, NethmiRodrigo commented on e2e/specs/mark-patient-deceased.spec.ts
> +  await test.step('When I click on the "Actions" button and select "Mark patient deceased"', async () => {
Shouldn't this be two separate steps?

2025-01-07 07:21 UTC, jayasanka-sack commented
Fixed with: https://github.com/openmrs/openmrs-esm-patient-chart/pull/2129

2025-01-07 07:21 UTC, closed without merging