(Refactor) O3-4274: Use useRef instead of useState for useVisitFormCallbacks
openmrs/openmrs-esm-patient-chart pull request #2157
Opened 2024-12-14 11:11 UTC by Bharath-K-Shetty

…tate

## Requirements

- [ ] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing.en-US#contributing-guidelines) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://om.rs/o3ui).
- [ ] My work includes tests or is validated by existing tests.

## Summary
This PR refactors the useVisitFormCallbacks hook by replacing the usage of useState with useRef. The primary goal of this change is to improve performance by avoiding unnecessary re-renders triggered by state updates. useRef is used to persist values across renders without causing re-renders, which is particularly beneficial in the case of form callbacks where state persistence is needed but without affecting component lifecycle.

This change ensures that the form callbacks are maintained correctly across renders, while reducing the overhead associated with state management in React.

Jira Issue: O3-4274

## Screenshots

## Related Issue

https://openmrs.atlassian.net/browse/O3-4274

## Other

2024-12-15 22:26 UTC, brandones requested changes
Thanks for this change, @Bharath-K-Shetty . Please clean up your code before submitting it. Remove the extra whitespace and strange comments.

2024-12-15 22:26 UTC, brandones commented on packages/esm-patient-chart-app/src/visit/visit-form/visit-form.component.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
I think it is preferable simply to include the ref in the dependency array, even though it will not change.

2024-12-15 22:26 UTC, brandones commented on packages/esm-patient-chart-app/src/visit/visit-form/visit-form.component.tsx
> +
```suggestion
  const visitFormCallbacksRef = useVisitFormCallbacks();
```

2024-12-15 22:26 UTC, brandones commented on packages/esm-patient-chart-app/src/visit/visit-form/visit-form.component.tsx
> +
```suggestion
            const onVisitCreatedOrUpdatedRequests = [...visitFormCallbacksRef.current.values()].map((callbacks) =>
```

Please don't add lots of unnecessary whitespace.

2024-12-15 22:26 UTC, brandones commented on packages/esm-patient-chart-app/src/visit/visit-form/visit-form.component.tsx
> +
Please get rid of the extra whitespace elsewhere in the PR.

2024-12-15 22:26 UTC, brandones commented on packages/esm-patient-chart-app/src/visit/visit-form/visit-form.component.tsx
> +                  name="visit-form-bottom-slot"
Why did you do this?

2024-12-15 22:26 UTC, brandones commented on packages/esm-patient-chart-app/src/visit/visit-form/visit-form.component.tsx
> +                  visitFormCallbacksRef={visitFormCallbacksRef} // Pass the ref instead
Don't include comments that won't make sense to someone reading this code later. The whole point of comments is to make code _less_ confusing.

2024-12-15 22:27 UTC, brandones commented
Please add a video demonstrating that everything still behaves as expected.

2024-12-20 13:18 UTC, Bharath-K-Shetty commented
Hey @brandones,I’ve made the changes as requested and updated the PR. Let me know if any further changes are needed.

Thank you

2025-01-03 16:14 UTC, brandones commented on packages/esm-patient-chart-app/src/visit/visit-form/visit-form.component.tsx
> +                  name="visit-form-bottom-slot"
Please don't resolve conversations without addressing the question being asked.

Why did you change the extension slot name?

2025-01-03 16:19 UTC, brandones requested changes

2025-01-03 16:19 UTC, brandones commented on packages/esm-patient-chart-app/src/visit/visit-form/visit-form.component.tsx
> -  // default values are cached so form needs to be reset when they change (e.g. when default visit location finishes loading)
Please restore this comment; it provides useful information for understanding what the code is doing, which is not obvious.

2025-01-03 16:19 UTC, brandones commented on packages/esm-patient-chart-app/src/visit/visit-form/visit-form.component.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
@Bharath-K-Shetty you actually need to respond to reviewer feedback, you can't just hit the "resolve conversation" button to make things go away

2025-01-03 16:19 UTC, brandones commented on packages/esm-patient-chart-app/src/visit/visit-form/visit-form.component.tsx
> -                    // Defaults to showing all possible visit types if recommended visits are not enabled
As above, please restore this comment

2025-01-03 16:43 UTC, Bharath-K-Shetty commented on packages/esm-patient-chart-app/src/visit/visit-form/visit-form.component.tsx
> -  // default values are cached so form needs to be reset when they change (e.g. when default visit location finishes loading)
Ok @brandones that was my fault.Thank you

2025-01-03 18:05 UTC, Bharath-K-Shetty commented on packages/esm-patient-chart-app/src/visit/visit-form/visit-form.component.tsx
> +                  name="visit-form-bottom-slot"
I changed the slot name from visit-form-top-slot to visit-form-bottom-slot because the original name (visit-form-top-slot) was causing a 404 error, indicating that the server could not find the requested resource. After troubleshooting, I updated the name to visit-form-bottom-slot, which resolved the issue and allowed the form to function as intended. This suggests that the visit-form-bottom-slot aligns with the correct configuration or extension setup expected by the system.

2025-01-10 15:04 UTC, brandones commented on packages/esm-patient-chart-app/src/visit/visit-form/visit-form.component.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
Ok if adding the ref in the dependency array causes a different eslint error that we would need to suppress anyway, then yes this is fine. Very strange though, that there is no dependency array that will not produce an ESLint error when a ref is used in the useEffect.

Do not click the "resolve conversation" button unless you yourself *opened* the conversation, otherwise the person you are talking with might not see your response. I opened this conversation with a request, so it's resolved either when I click the "resolved" button or when I respond with something that suggests that I've acknowledged what you've written and think my question is resolved. Hope this is clear and helpful for your future GitHub use.

2025-01-10 15:09 UTC, brandones requested changes

2025-01-10 15:09 UTC, brandones commented on packages/esm-patient-chart-app/src/visit/visit-form/visit-form.component.tsx
> +                  name="visit-form-bottom-slot"
That's very surprising, and a separate bug from this ticket. I'm fine with you addressing it in this PR, but you need to document the bug. Please provide screenshots showing the error.

Whatever the problem is, this is pretty certainly not the solution, since there is already a `visit-form-bottom-slot` in existence, on line 774 of this file. If you're not sure how the extension system works, read the docs.

2025-01-10 15:14 UTC, brandones commented
Also, you can use the "Request re-review" button instead of pinging people on Slack.

![image](https://github.com/user-attachments/assets/641a2d7a-ed64-4274-9bde-3d565c050bdb)

2025-01-16 18:03 UTC, brandones requested changes
This just keeps getting worse... I'm going to close this PR. If you'd like to make a fresh start of it, feel free. Tag @chibongho as reviewer in that case, since he opened the ticket, I think he has the best understanding of what this should look like.

2025-01-16 18:03 UTC, brandones commented on packages/esm-patient-chart-app/src/visit/visit-form/visit-form.component.tsx
> +                  name="visit-form-top-slot"
Basically same feedback as before... there is already a top slot, at the top of the component. This is a different slot, at the bottom of the component.

2025-01-16 18:03 UTC, closed without merging

2025-01-16 18:22 UTC, Bharath-K-Shetty commented
@brandones Thank you for the feedback and your patience. I'll take a fresh look and ensure a cleaner implementation if I revisit this. I'll tag @chibongho for guidance next time.