03 1113:(enhancement) Make calendar icon on forms clickable to open date-picker
openmrs/openmrs-esm-patient-chart pull request #575
Opened 2022-02-24 14:49 UTC by donaldkibet

## Requirements

- [x] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [x] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).
- [x] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary

- Bump form-entry to include fix for date-picker to launch on clicking the calendar ico
- Remove `encounter date time` from form-entry form-wrapper
- Improve better error handling of form fields error when submitting the form, this is because in the `fieldErrors` are not returned by the API
- Add ability to display the currently open form on workspace header, [design](https://app.zeplin.io/project/60d59321e8100b0324762e05/screen/61f03e8f470f50a7aa88c557)

## Screenshots

![forms-enhancement](https://user-images.githubusercontent.com/28008754/155546881-c7ef3dc7-6315-464b-8c7d-ba68df833870.gif)

## Issue
https://issues.openmrs.org/projects/MF/issues/O3-1127
https://issues.openmrs.org/projects/MF/issues/O3-1113

## Other

*None.*

2022-02-24 23:22 UTC, brandones requested changes

2022-02-24 23:22 UTC, brandones commented on packages/esm-patient-chart-app/src/workspace/workspace-window.component.tsx
> +  const workspaceTitle = additionalProps?.workspaceTitle ? additionalProps.workspaceTitle : workspaces[0]?.title ?? '';
```suggestion
  const workspaceTitle = workspaces[0]?.additionalProps['workspaceTitle'] ?? workspaces[0]?.title ?? '';
```

2022-02-25 18:18 UTC, brandones commented on packages/esm-patient-chart-app/src/workspace/workspace-window.component.tsx
> +    (workspaces[0]?.additionalProps && workspaces[0]?.additionalProps['workspaceTitle']) ?? workspaces[0]?.title ?? '';
```suggestion
    workspaces[0]?.additionalProps?.['workspaceTitle'] ?? workspaces[0]?.title ?? '';
```

2022-02-25 18:18 UTC, brandones approved these changes

2022-02-25 19:57 UTC, jonathandick commented
Thanks @donaldkibet and @brandones

2022-02-25 19:57 UTC, merged