Add tests for vitals-biometric form submission
openmrs/openmrs-esm-patient-chart pull request #619
Opened 2022-03-23 08:52 UTC by nanfuka

## Requirements

- [ ] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide).
- [ ] My work includes tests or is validated by existing tests.

## Summary

## Screenshots

## Related Issue

## Other

2022-04-01 06:08 UTC, nanfuka commented
@denniskigen kindly review

2022-04-04 18:16 UTC, denniskigen requested changes
Nice work @nanfuka. Generally looks good save for a warning in the test run. I'd also recommend using more realistic test values for values like temperature, pulse and so forth.

2022-04-04 18:16 UTC, denniskigen commented on packages/esm-patient-vitals-app/src/vitals/vitals-biometrics-form/vitals-biometrics-form.component.test.tsx
> +      userEvent.click(saveButton);
Running this test locally throws this warning:

<img width="587" alt="Screenshot 2022-04-04 at 21 07 40" src="https://user-images.githubusercontent.com/8509731/161605055-9b09aad7-a9d2-4843-883a-afb77d684143.png">

To remedy it, you'd need to pass an `event` object to `savePatientVitalsAndBiometrics` in the component and then call `.preventDefault()` on it. Like so:

```js
const savePatientVitalsAndBiometrics = (event: SyntheticEvent) => {
  event.preventDefault();
  // ...
}
```

2022-04-05 12:53 UTC, denniskigen approved these changes

2022-04-05 19:18 UTC, merged