O3-1196: Tablet design (horizontal): "Select local photo instead" button is hidden in attachment popup
openmrs/openmrs-esm-patient-chart pull request #632
Opened 2022-03-31 01:08 UTC by 99sumedha

## Requirements

- [x] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [x] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide).
- [x] My work includes tests or is validated by existing tests.

## Summary

Adjust the size of the camera feed area respective to the height of the tablet horizontal view.

## Screenshots

![image](https://user-images.githubusercontent.com/27495258/160955870-c4cc68d1-345e-4820-b642-37471c5c00a1.png)

## Related Issue

https://issues.openmrs.org/browse/O3-1196

## Other

2022-03-31 15:55 UTC, brandones requested changes

2022-03-31 18:13 UTC, 99sumedha commented on packages/esm-patient-attachments-app/src/attachments/camera-upload.scss
> +@media (max-height: $breakpoint-tablet-min){
Shall I set it to 600px?

2022-03-31 21:55 UTC, brandones commented on packages/esm-patient-attachments-app/src/attachments/camera-upload.scss
> +@media (max-height: $breakpoint-tablet-min){
No, it should just be based on width, not height.

2022-04-01 10:59 UTC, 99sumedha commented on packages/esm-patient-attachments-app/src/attachments/camera-upload.scss
> +@media (max-height: $breakpoint-tablet-min){
Sure I will make the changes and commit :)

2022-04-01 12:44 UTC, 99sumedha commented
@brandones new changes committed :)

2022-04-01 17:26 UTC, brandones approved these changes

2022-04-02 02:19 UTC, merged

2022-04-03 21:37 UTC, 99sumedha commented
Thank you :)