O3-1281 Visit Note - Add Ability to Mark Primary and Secondary Diagnoses
openmrs/openmrs-esm-patient-chart pull request #732
Opened 2022-06-28 09:48 UTC by abertnamanya

## Requirements

- [ ] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide).
- [ ] My work includes tests or is validated by existing tests.

## Summary

1. Form allows selection of multiple primary diagnosis and multiple secondary diagnosis 
2. Plus diagnosis could be detached/removed from respective category 
3. After submission diagnoses are displayed in the Visit Note data table

## Screenshots

https://user-images.githubusercontent.com/19745793/176147752-e0b93bd2-b803-42a7-8039-6a19f731c6bd.mp4

## Related Issue

https://issues.openmrs.org/browse/O3-1281
## Other

2022-06-28 09:50 UTC, abertnamanya commented
Hi @ZacButko Here is the PR, But I did skip the tests never wanted to delay this ticket could you find time and resolve the tests for the Visit Note.
Thank you.

2022-07-07 12:37 UTC, ibacher requested changes
@abertnamanya Thanks for this! Obviously, we need to fix the tests before this can be merged and there are one or two minor points I've raised in comments below.

2022-07-07 12:37 UTC, ibacher commented on packages/esm-patient-notes-app/src/types/index.ts
> +  name: {
Do we care about the name property at all? We only really need to include the properties we care about (we should use `display`).

2022-07-07 12:37 UTC, ibacher commented on packages/esm-patient-notes-app/src/types/index.ts
> +export interface conceptNames {
Should be capitalised, but again, I don't think this is useful information to maintain...

```suggestion
export interface ConceptNames {
```

2022-07-07 12:37 UTC, ibacher commented on packages/esm-patient-notes-app/src/notes/visit-notes.resource.ts
> +  return conceptMapping.find((concept) => concept.conceptReferenceTerm.display);
What is this supposed to do?

2022-07-07 12:37 UTC, ibacher commented on packages/esm-patient-notes-app/src/notes/visit-notes.resource.ts
> +    confirmed: true,
Why do we default to assuming a diagnosis is confirmed? ("Confirmed" in this context generally means "we have a lab test that proves the patient has x")

2022-11-14 21:19 UTC, hadijahkyampeire commented
@abertnamanya are you still available to work on this or you would prefer someone to take it on?

2022-11-15 06:34 UTC, abertnamanya commented
> @abertnamanya are you still available to work on this or you would prefer someone to take it on?

Dear @hadijahkyampeire, this was taken over by @icrc-loliveira in this PR https://github.com/openmrs/openmrs-esm-patient-chart/pull/757
**Regards**,

2022-11-15 08:54 UTC, hadijahkyampeire commented
Oh that’s okay, then we should close this PR since it’s work is already merged.

2022-11-15 08:54 UTC, closed without merging