Implement Patient List history in Patient Header
openmrs/openmrs-esm-patient-chart pull request #927
Opened 2023-01-04 22:21 UTC by nanfuka

## Requirements

- [ ] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide).
- [ ] My work includes tests or is validated by existing tests.

## Summary

## Screenshots

## Related Issue
https://issues.openmrs.org/browse/O3-803
[Screencast from 05-01-23 01:14:02.webm](https://user-images.githubusercontent.com/29108523/210660900-aa96590d-52fe-4522-91d1-bdee11f017e7.webm)

## Other

2023-01-09 10:25 UTC, vasharma05 commented
A few improvements:
1. The video should be part of the Screenshots section.
2. Why do we click "Show More" to get the list. What we can do is we can show say 5 lists and if there are more than 5 lists, we display a "Show all" button to get the whole list.

2023-01-09 10:30 UTC, vasharma05 commented on packages/esm-patient-chart-app/src/banner/contact-details/patientList.resource.tsx
> +  return {
The return of a hook should always be memoised for lower re-renders

2023-01-09 10:30 UTC, vasharma05 commented on packages/esm-patient-medications-app/translations/en.json
> -  "searchFieldPlaceholder": "Search for a drug or orderset (e.g. \"Aspirin\")",
Please revert this file.
Thanks!

2023-01-12 14:38 UTC, vasharma05 requested changes
Great work @nanfuka!

I don't want to demotivate you, but there are some places we can focus. Just some changes required in the code writing.

The work looks great!
Thanks!

2023-01-12 14:38 UTC, vasharma05 commented on packages/esm-patient-chart-app/src/banner/contact-details/contact-details.component.tsx
> +          iconDescription="Toggle patient List Details"
This text needs to be translated

2023-01-12 14:38 UTC, vasharma05 commented on packages/esm-patient-chart-app/src/banner/contact-details/contact-details.component.tsx
> +          style={{ marginTop: '-0.25rem' }}
Please do this via a class. We don't usually use inline styling.
Thanks!

2023-01-12 14:38 UTC, vasharma05 commented on packages/esm-patient-chart-app/src/banner/contact-details/contact-details.component.tsx
> +          {showPatientListDetails ? t('seeLess', 'See less') : t('seeAll', 'See All')}
`See less` and `See All` Please confirm from the designs that should the starting letter of second word should be capital or lower case.
Thanks!

2023-01-12 14:38 UTC, vasharma05 commented on packages/esm-patient-chart-app/src/banner/contact-details/contact-details.component.tsx
> +        })()}
This looks okay to create a function and then calling it, but I believe this should not be done in the render. Instead, I believe we can save this whole logic using `useMemo` hook in a variable like:

```suggestion
        const patientLists = useMemo(() => {
          if (isLoading) return <SkeletonText />;
          if (formattedPatientLists?.length && !showPatientListDetails) {
            return (
              <ul>
                {formattedPatientLists.slice(0, 5).map((r) => (
                  <li key={r.uuid} className={styles.relationship}>
                    <ConfigurableLink className={styles.link} to={`\${openmrsSpaBase}/patient-list/${r.uuid}`}>
                      {r.display}
                    </ConfigurableLink>
                  </li>
                ))}
              </ul>
            );
          } else if (formattedPatientLists?.length && showPatientListDetails) {
            return (
              <ul>
                {formattedPatientLists.map((r) => (
                  <li key={r.uuid} className={styles.relationship}>
                    <ConfigurableLink className={styles.link} to={`\${openmrsSpaBase}/patient-list/${r.uuid}`}>
                      {r.display}
                    </ConfigurableLink>
                  </li>
                ))}
              </ul>
            );
          }
          return <p>--</p>;
        }, [<---dependencies--->])
        
        return (
        <div>
            <Header Code />
            {patientLists}
        </div>
```

Also, we haven't done any error handling, please add that too.
Thanks!

2023-01-12 14:38 UTC, vasharma05 commented on packages/esm-patient-chart-app/src/banner/contact-details/contact-details.scss
> +  float: right;
Please don't use float

Either use flex with `justify-content: space-between` in the parent element or give `margin-left: auto` to the button, whichever works.

Thanks!

2023-01-12 14:38 UTC, vasharma05 commented on packages/esm-patient-chart-app/src/banner/contact-details/patientList.resource.tsx
> +    ];
You can remove this links from the type, since it's not used anywhere

2023-01-12 14:38 UTC, vasharma05 commented on packages/esm-patient-chart-app/src/banner/contact-details/patientList.resource.tsx
> +    ];
Same for other links in the same type

2023-01-12 14:38 UTC, vasharma05 commented on packages/esm-patient-chart-app/src/banner/contact-details/patientList.resource.tsx
> +  ];
Same here

2023-01-12 14:38 UTC, vasharma05 commented on packages/esm-patient-chart-app/src/banner/contact-details/patientList.resource.tsx
> +  const { data, error, isValidating } = useSWR<{ data: PatientListResponse }, Error>(
```suggestion
  const { data, error, isValidating } = useSWR<FetchResponse<PatientListResponse>, Error>(
```

2023-01-12 14:38 UTC, vasharma05 commented on packages/esm-patient-chart-app/src/banner/contact-details/patientList.resource.tsx
> +    `${cohortUrl}/cohortmember?patient=${patientUuid}&v=default`,
If `v` is default, we don't need to send `v`.

2023-01-12 14:38 UTC, vasharma05 commented on packages/esm-patient-chart-app/src/banner/contact-details/patientList.resource.tsx
> +  const { data, error, isValidating } = useSWR<{ data: PatientListResponse }, Error>(
What are the chances that the response will change. 

If not much, then we can move to `useSWRImmutable`

2023-01-16 15:00 UTC, vasharma05 approved these changes
Great work!
Thanks!

2023-02-01 20:10 UTC, denniskigen commented
I've added a few tweaks:

<img width="1148" alt="patient-list-history-in-banner" src="https://user-images.githubusercontent.com/8509731/216151294-b4b30dbe-d005-46f8-b585-60bf12166d95.png">

Primarily, clicking on the `See all` link should now navigate the user to the patient lists page. This is now just a link instead of a button and seems more in line with what the design provides for https://app.zeplin.io/project/60d59321e8100b0324762e05/screen/60d5db4e6061e404a1a2191f.

2023-02-01 20:22 UTC, denniskigen approved these changes

2023-02-01 20:28 UTC, denniskigen commented on packages/esm-patient-chart-app/src/banner/contact-details/patientList.resource.tsx
> +    } else {
This logic is gone in the latest commit, as we've done away with the `See all` button altogether in favour of a simple link to the patient lists page.

2023-02-01 20:48 UTC, merged